// Generated by scripts/generate-protocol.mjs. Do not edit by hand.

export const protocolMetadata = {
  codexCliVersion: "0.162.0",
  transport: "jsonl" as const,
  includesExperimentalApi: true,
} as const;
